desc "Compile extensions"
task :compile do
  scs = File.expand_path("../../vendor/scs", __dir__)
  Dir.chdir(scs) do
    sh "make"
  end
end

unless Rake::Task.task_defined?("default")
  task default: :compile
end
